### ISSUE TITLE
Smoketest docker containers do not connect as they should when run on Travis

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/intranet#70]
```
smoketest_tests |   Scenario: Test Environment    # features/happypath/00_check_environment.feature:4
smoketest_tests |   ---> Seeding test users <---
smoketest_tests |   [[], ["PHP Warning:  mysqli_real_connect(): (HY000/2002): Connection refused in /bedrock/web/wp/wp-includes/wp-db.php on line 1538\nWarning: mysqli_real_connect(): (HY000/2002): Connection refused in /bedrock/web/wp/wp-includes/wp-db.php on line 1538\n", "Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can\xE2\x80\x99t contact the database server at `mariadb`. This could mean your host\xE2\x80\x99s database server is down.\n"], 1]
smoketest_tests |   undefined method `strip!' for nil:NilClass (NoMethodError)
smoketest_tests |   /features/support/users_helper.rb:51:in `create_user!'
smoketest_tests |   /features/support/users_helper.rb:27:in `add_user!'
smoketest_tests |   /features/support/hooks.rb:5:in `Before'
smoketest_tests |     Given I show my environment # eatures/step_definitions/common.rb:6
smoketest_tests | 
smoketest_tests | Failing Scenarios:
smoketest_tests | cucumber features/happypath/00_check_environment.feature:4 # Scenario: Test Environment
smoketest_tests | 
```

This is working fine on local containers.

**Comment by tatyree** [comment]
This was fixed some time ago–uncertain of exact PR.  Closing.
